/*
 * This file is generated by jOOQ.
 */
package jp.co.sysystem.training.guide.jooq;


import java.util.Arrays;
import java.util.List;

import jp.co.sysystem.training.guide.jooq.tables.FileHistory;
import jp.co.sysystem.training.guide.jooq.tables.MarkdownFile;
import jp.co.sysystem.training.guide.jooq.tables.MarkdownFileHistory;
import jp.co.sysystem.training.guide.jooq.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trainingguidebook extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>trainingguidebook</code>
     */
    public static final Trainingguidebook TRAININGGUIDEBOOK = new Trainingguidebook();

    /**
     * 編集記録表
     */
    public final FileHistory FILE_HISTORY = FileHistory.FILE_HISTORY;

    /**
     * マークダウンファイル管理テーブル
     */
    public final MarkdownFile MARKDOWN_FILE = MarkdownFile.MARKDOWN_FILE;

    /**
     * マークダウンファイル変更履歴テーブル
     */
    public final MarkdownFileHistory MARKDOWN_FILE_HISTORY = MarkdownFileHistory.MARKDOWN_FILE_HISTORY;

    /**
     * The table <code>trainingguidebook.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Trainingguidebook() {
        super("trainingguidebook", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FileHistory.FILE_HISTORY,
            MarkdownFile.MARKDOWN_FILE,
            MarkdownFileHistory.MARKDOWN_FILE_HISTORY,
            User.USER
        );
    }
}
